site_name: kode
site_description: A fast, local coding agent for your terminal
site_url: https://github.com/GeorgePearse/kode
repo_url: https://github.com/GeorgePearse/kode
repo_name: kode

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: install.md
    - Getting Started: getting-started.md
  - Usage:
    - Commands: slash-commands.md
    - Configuration: config.md
    - Authentication: authentication.md
    - Theme Configuration: THEME_CONFIG.md
  - Advanced:
    - Advanced Topics: advanced.md
    - Sandbox Mode: sandbox.md
    - Execution: exec.md
  - Architecture:
    - Fork Enhancements: fork-enhancements.md
  - Contribution:
    - Contributing: contributing.md
    - CLA: CLA.md
  - Legal:
    - License: license.md
