site_name: kode
site_description: A fast, local coding agent for your terminal
site_url: https://georgepearse.github.io/kode/
repo_url: https://github.com/GeorgePearse/kode
repo_name: kode

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: install.md
    - Quick Start: getting-started.md
    - Getting Started Details:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  - Usage:
    - Commands: slash-commands.md
    - Configuration: config.md
    - Authentication: authentication.md
    - Theme Configuration: THEME_CONFIG.md
    - Basic Usage: usage/basic.md
  - Advanced:
    - Advanced Topics: advanced.md
    - Sandbox Mode: sandbox.md
    - Execution: exec.md
    - MCP Integration: upstream-mcp-implementation-guide.md
    - MCP Reuse Strategy: upstream-mcp-reuse-strategy.md
  - Features:
    - Auto Drive:
      - Architecture: features/auto-drive/architecture.md
      - State Inventory: auto-drive-state-inventory.md
      - Phase Migration: auto-drive-phase-migration-TODO.md
    - Prompts: prompts.md
    - Integration - Zed: integration-zed.md
    - Auto QA: auto-qa.md
  - Architecture:
    - Fork Enhancements: fork-enhancements.md
    - Overview:
      - Pipeline: architecture/pipeline.md
      - Overview: architecture/overview.md
    - Aggregation:
      - Overview: aggregation/overview.md
      - MOA: aggregation/moa.md
      - MCTS: aggregation/mcts.md
      - RSA: aggregation/rsa.md
  - Technical Deep Dives:
    - History & Caching:
      - History Render Cache Bridge: history_render_cache_bridge.md
      - History State Schema: history_state_schema.md
      - History Debugging: dev/history-debugging.md
      - History Invariants: dev/history-invariants.md
    - TUI & UI:
      - Card Themes: tui-card-themes.md
      - Chat Widget Refactor: tui-chatwidget-refactor.md
    - Upstream:
      - ACP Merge: upstream-acp-merge.md
      - MCP Implementation: upstream-mcp-implementation-guide.md
    - Performance:
      - Benchmarks: performance/benchmarks.md
    - Configuration:
      - Config Reference: configuration/config.md
    - API:
      - Types: api/types.md
  - Maintenance:
    - Release Management: release_management.md
    - Prompt Architecture: maintenance/prompt-architecture.md
    - Upstream Diff: maintenance/upstream-diff.md
  - References:
    - References: references.md
    - FAQ: faq.md
    - Platform Sandboxing: platform-sandboxing.md
    - Markdown Showcase: markdown_showcase.md
    - Open Source Fund: open-source-fund.md
    - ZDR: zdr.md
    - Experimental: experimental.md
    - Homebrew: HOMEBREW.md
    - Interrupt & Resume: interrupt-resume-postmortem.md
  - Contribution:
    - Contributing: contributing.md
    - CLA: CLA.md
  - Legal:
    - License: license.md
