name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-docs.txt

      - name: Build documentation
        run: mkdocs build

      - name: Deploy to GitHub Pages
        if: success()
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # Create a fresh repo in the site directory for deployment
          cd site

          # Add .nojekyll to disable Jekyll processing
          touch .nojekyll

          # Initialize git repo
          git init
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Deploy documentation"

          # Configure credential helper
          git config --local credential.helper store
          echo "https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

          # Push to gh-pages
          git push -f https://github.com/${{ github.repository }}.git HEAD:gh-pages
